---

- hosts: eip
  become: true
  gather_facts: false
  serial: 1

  tasks:

  - name: Install columnstore
    package:
      name: MariaDB-columnstore-engine
    environment:
      MCS_USE_S3_STORAGE: "1"
      MCS_S3_BUCKET: "cs-s3-stage"
      MCS_S3_ENDPOINT: "s3.{{ lookup('env', 'AWS_DEFAULT_REGION') }}.amazonaws.com"
      MCS_S3_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      MCS_S3_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      MCS_S3_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"

  - name: Install columnstore
    tags: cmapi
    dnf:
      name: https://cspkg.s3.amazonaws.com/cmapi/latest/mariadb-columnstore-cmapi-1.2.rpm
      disable_gpg_check: true
